version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16-bullseye
    volumes:
      - ..:/workspace
    command: sleep infinity
    networks:
      - frontend
      - backend

  db:
    restart: unless-stopped
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    ports:
      - "27017:27017"

volumes:
  mongo_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
